### ISSUE TITLE
2020 08 14

### ISSUE THREAD

**Issue by sump99** [DKU-STUDY/TodayReview#117]

**Comment by JunilHwang** [comment]
## 회사일
- 오늘은 회사일을.. 거의 하지 않았다.

## 기능반 출근
- 앞으로 한 달 정도 재택근무를 하는 날에는 서울 디지텍 고등학교 기능반에 와서 학생들을 가르치게될 것 같다.
- 기능대회 문제..ㄴ ㅓ무 극혐

**Comment by sump99** [comment]
## JavaScript 기초
- [WEB2 JavaScript - 8.웹브라우저 제어](https://www.youtube.com/watch?v=S62m_ddSls4&list=PLuHgQVnccGMBB348PWRN0fREzYcYgFybf&index=8) 생활코딩 유튜브 강의 실습 및 JavaScript 문법 파악

## 컴활 1급 필기 문제풀이
- [컴활1급필기 - 자주 출제되는 기출문제 81~100번 유튜브 강의](https://www.youtube.com/watch?v=WOnCybrh5Y0&t=1276s) 컴활 1급 필기 3과목 데이터베이스 일반 부분에서 SQL문 문법 위주로 문제 풀이

## Java를 이용한 특정 자료구조 구현
- [자료구조 알고리즘 - Queue구현하기 in Java](https://www.youtube.com/watch?v=W3jNbNGyjMs) 유튜브 강의 실습 및 코드 변형

**Comment by Jaewon0702** [comment]
Programmers
==============
[level 02. 큰 수 만들기 ](https://github.com/DKU-STUDY/Algorithm/pull/373)
계속 고민하다가 솔루션을 보고 이해하는 쪽을 택하였다. 숫자를 앞에서부터 그 전값보다 크면 값을 바꾸고 작으면 뒤에 추가하는 식으로 큰 수를 찾는 방식이었다. 내가 itertools의 combinations( ) 함수를 이용하여 풀려던 것과는 전혀 다른 방식이라서 흥미로웠다. @JunilHwang 님이 리뷰를 해주셨는데, 중첩 반복문을 사용하지 않는 방식을 고민해보라고 하셨다. 내일모레 다시 풀어봐야겠다.
**black 스타일 코드가 띄어쓰기가 있으면 제대로 파일을 인식하지 못한다는 것을 알아냈다. 앞으로 코드에 black을 적용하고 싶다면 띄어쓰기 대신 _를 사용하자. 예) 역세권_분석**

인문학 독서
===========
장하석, <과학, 철학을 만나다>
--------------------------------------------
**2부 과학철학에 실천적 감각 더하기
8장 물은 H2O인가?**
4. 유기화학에서 내려준 H2O의 결론
유형 이론(type theory) : 물질을 분자의 구성내용을 기반으로 분류하자.
물 H-O-H
에틸알코올 C2H5-O-H
에테르 C2H5-O-C2H5
에틸알코올은 물에 H가 빠지고 에틸기(C2H5)가 추가돼서 만들어진다.
알렉산더 윌리엄슨의 물 유형 이론은 물의 화학식이 H2O일 거라는 가정에서 출발하였지만, 분자구조의 진상을 대강 표현하며 그냥 굳어졌다. ---> **논리적으로 볼 때는 허점이 있지만 실용적이다!**

5. 원자론의 역사가 과학교육에 주는 교훈
**"과학자들이 어떤 연구과정과 어떤 사고방식으로 그 결과를 얻어냈는가를 일반인들이 알아야 한다. 그런 과학 방법론의 본질을 알지 못하는 사람이 과학의 결과는 믿는 것은 맹신에 불과하고, 믿지 않는다면 근거 없는 비이성적인 거부이다. "**

8장요약
- 물분자가 H2O라는 것은 다들 아는 과학적 상식이다. 그러나 이런 상식들을 비판적으로 재조명해볼 필요가 있다.
-'화학적 원자론의 아버지'라 불리는 돌튼은 물분자가 HO라고 생각했다. 직접 관측되지 않은 내용이기 때문에, 의식적으로 가장 간단한 가설을 채택한 것이다. 아보가드로는 확실한 근거 없이 H2O라는 분자식을 제안했고, 그의 이론은 일반적으로 채택되지 못했다.
- 유기화학에서 성공적이었던 분자 모델들은 '원자가'의 개념을 낳았으며, 그에 따라 H2O 등 여러 가지 분자식이 대부분 정립되었다. 1850년대에 와서야 이루어지기 시작한 일이다.
- 이러한 상식적 과학지식을 확립하는 과정이 얼마나 복잡하고 힘겨웠던가를 알면 과학탐구의 본질을 배우는 데 도움이 된다.

9장 물은 항상 100도에서 끓는가?
1. 고정하기가 힘들었던 물의 비등점
[조지 아담스] 섭씨 95도에서 물은 끓기 시작한다.

2. 물 끓여보기
물은 95도에서 거품이 수면을 뚫는다. 100도에서 안정되고 계속 끓이면 약 101도까지 올라간다.
[게이 뤼삭] 금속 그릇 - 100도에서 끓는다.    유리그릇 - 101.2도    양은 - 97도

3. 신기하고도 복잡한 거품 형성
"거품이 형성될 때 물은 열을 크게 손실한다."
"거품 형성이 느리게 일어나면 온도가 올라간다. 이를 초가열(superheating) 현상이라 한다." 
표면장력 : 거품을 찌부려뜨리는 역할 a 1/ 반지름

4. 들룩 수난기
"온도가 높아질수록 공기는 더 빠지고, 그러면 끓기가 더 어려워지고, 그러면 물은 열을 잃는 속도가 줄어들고, 열이 더 축적되어 더 심한 Superheating이 일어난다."

5. 물리학이냐 공학이냐
공학자들이 가장 기본적으로 관심을 두는 내용은 끓는 물을 통해서 열이 얼마나 빨리 전달되는가 하는 것이고, 그 물 자체의 온도에는 별 관심이 없다.

6. 전문화와 생활과학
"과학이 발달할수록 각 개인의 전문분야가 좁아지는 것은 피할 수 없는 현대적 추세이다. 지식의 범위와 깊이는 계속 엄청나게 늘어가고 있지만 인간 개인의 능력이란 많이 늘어날 수 없기 때문이다."

9장 요약
- 물이 H2O라는 것과 마찬가지로, 물이(1기압 하에서) 항상 100도에서 끓는다는 것도 다들 아는 과학상식이다. 이 역시 비판적 사고를 적용해볼 수 있는 좋은 예가 된다.
- 18, 19세기 자료를 보면 물의 비등점이 명확하게 정해지지 않았다는 실험보고서가 자주 나온다. 물을 끓이면서 잘 관찰해보면 쉽게 확인할 수 있다.
- 물을 넣고 끓이는 그릇의 재질, 열 공급원의 온도, 그리고 물에 녹아 있는 기체의 양 등 여러 가지 요인에 따라 끓는 형태와 온도가 크게 달라진다는 보고도 쉽게 재현할 수 있다. 끓을 때 이루어져야 하는 거품 형성은 복잡한 과정이다.
- 옛날 과학자들이 널리 가지고 있던 이러한 지식을 현재는 소수의 전문가만 알고 있다. 물을 끓이는 것과 같은 일상적인 현상에 대해 일반인과 보통 과학자가 제대로 알지 못해야 할 타당한 이유는 없다.
- '물은 항상 100도에서 끓는다.'고 암송하는 것은 의미 있는 과학지식이라 할 수 없고, 과학적 탐구의 본질을 이해하는 행동은 더더욱 아니다. 주입식 교육의 허점이 잘 드러나는 사례이다. 

오늘 아버지가 학회를 가셨다가 3일 만에 돌아오셔서 부모님과 한잔하였다. 55도 보드카를 레몬즙을 타서 마셨다. 엄청 취하네.... 평소였으면 다른 책을 더 읽거나 파이썬 공부를 좀 더 할 텐데 취기가 계속 올라와서 오늘은 여기까지만 하고 일찍 잔다.

**Comment by Jaewon0702** [comment]
> ## JavaScript 기초
> * [WEB2 JavaScript - 8.웹브라우저 제어](https://www.youtube.com/watch?v=S62m_ddSls4&list=PLuHgQVnccGMBB348PWRN0fREzYcYgFybf&index=8) 생활코딩 유튜브 강의 실습 및 JavaScript 문법 파악
> 
> ## 컴활 1급 필기 문제풀이
> * [컴활1급필기 - 자주 출제되는 기출문제 81~100번 유튜브 강의](https://www.youtube.com/watch?v=WOnCybrh5Y0&t=1276s) 컴활 1급 필기 3과목 데이터베이스 일반 부분에서 SQL문 문법 위주로 문제 풀이
> 
> ## Java를 이용한 특정 자료구조 구현
> * [자료구조 알고리즘 - Queue구현하기 in Java](https://www.youtube.com/watch?v=W3jNbNGyjMs) 유튜브 강의 실습 및 코드 변형

처음 뵈는 분이시네요. 반갑습니다~

**Comment by khw970421** [comment]
js interview 리뷰하기 , step05 좀더 이해하며 5.5 내용만들어 다음파트위해서 개념적 정리  
https://github.com/khw970421/js-interview/blob/master/const/project5.5.js
java 개념정리 2일차 : 클래스멤버와 인스턴스멤버 차이 이해 (static vs non-static)
java 메모리 관련 이해 
메소드 오버로딩 이해
동등연산자 이해 (== 메모리주소적 동등 의미)
String a = "init"
String aa = new String("init"); 과의 개념적 차이 이해
 문자열 비교를 통해서는( equals) 같지만
String a = "init"은 Heap의 영역의 String pool 위치에 저장되나
String aa = new String("init")은 Heap 위치로 서로다른 주소에 저장되어 동등연산자로 비교하면 false된다.

**Comment by JeongShin** [comment]
알고 풀이 후 알바 갔다온 뒤 휴식 ,,

**Comment by eyabc** [comment]
- 한국 관광공사 API 탐색 및 기획 -> 코리아 사진 갤러리의 개발 및 저작권 문의 -> 사용불가
- 스터디 튜토리알 제작
- 식스샵 입사지원

- [냉동밥을 더 맛있게 먹는 노하우! 덜 딱딱해지게 만드는 데우기 방법은요... /효율주부 팁
](https://www.youtube.com/watch?v=rznBdMhEY9I&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=2&t=0s)
- [괴로움에서 벗어나기 위해 먼저 해야 할 일
](https://www.youtube.com/watch?v=R6Z3Irg6mVQ&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=7&t=0s)
- [급똥 해방 효과 100% 꿀팁! 여기만 누르면 급똥 피할 수 있다?!
](https://www.youtube.com/watch?v=e95vtzVCzrE&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=6&t=0s)
- [[바른의학26-1] [코로나 16편1부] 유전자 증폭검사와 신속면역항체검사의 문제점 진단. 코로나 검사법의 궁금증을 풀어드립니다. Q RT-PCR, Antibody test
](https://www.youtube.com/watch?v=jEXLRpvthH4&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=5&t=0s)
- [[바른의학26-2] [코로나 16편2부] 유전자 증폭검사와 신속면역항체검사의 문제점 진단. 코로나 검사법의 궁금증을 풀어드립니다. Q RT-PCR, Antibody test
](https://www.youtube.com/watch?v=kcK6EC0hlH4&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=4&t=0s)
- [내가 컨퍼런스에 다니는 이유
](https://www.youtube.com/watch?v=orv5ibWzkMg&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=3&t=0s)
- [프로그래머로 취업할 때 자신을 어필하는 방법
](https://www.youtube.com/watch?v=D1CggHI2Adc&list=LLlvIZ9GEn_ygW3Hxmp0lqag&index=2&t=0s)
