### ISSUE TITLE
2020 08 15

### ISSUE THREAD

**Issue by khw970421** [DKU-STUDY/TodayReview#118]
1. 경제 공부하기 (주식 관련 ) 
자산 = 부채 +  자본
자본 = 자본금 + 자본잉여금 +이익잉여금 ...

2. java 클래스 변수와 인스턴스 변수를 객체화 했을때 값의 변화

   public class h {
    public static void main(String[] args) {
        Field myField1 = new Field();   // 인스턴스 생성
        Field myField2 = new Field();   // 인스턴스 생성
        myField1.classVar = 100;            // 클래스 변수의 값을 변경

        System.out.println(Field.classVar); // 클래스 변수 참조   100
        System.out.println(myField1.classVar);                              //100
        System.out.println(myField2.classVar + "\n");                   //100

        myField1.instanceVar = 1000;
        System.out.println(myField1.instanceVar);                     //1000
        System.out.println(myField2.instanceVar + "\n");           //20
    }
}

class Field {
    static int classVar = 10; // 클래스 변수 선언
    int instanceVar = 20;     // 인스턴스 변수 선언
}

클래스 변수는 자원을 공유하므로 값이 변경되면 다른 참조하는 곳들도 변한 값이 되나
인스턴스 변수는 공유하지않아 값이 변경되어도 다른 객체들이 참조와 영향이없다.

**Comment by Jaewon0702** [comment]
인문학 독서
===========
장하석, <과학, 철학을 만나다>
------------------------------------
2부 과학철학에 실천적 감각 더하기
10장 집에서 하는 전기화학
1. 전지(battery)의 발명
이탈리아의 볼타(Alessandro Volta)
집에서도 간단하게 만들 수 있다.

2. 전기화학은 민중과학?
니콜슨(William Nicholson) ---->1797년에 학술지 창간
**어떤 저자의 논문이던지 본인이 판단하기에 흥미로우면 게재하였다.**
당시 런던의 왕립학회 공식 학회지는 회원(fellow)이 아니면 원고를 보내지 못하였다.
**3년 후 니콜슨과 칼라일은 최초로 물을 산소와 수소로 전기 분해한 논문을 발표하였다.**
**-->그 때까지 아무런 확실한 관계가 없다고 생각되었던 전기와 화학을 연결하였다.**

오늘 이모네 가족이 2주 뒤에 프랑스 파리로 이사가셔서 짐 정리하는 거 도와드리고 왔다. 하루종일 일하느라 공부는 많이 못하였다. 대신 세탁기, 냉장고, 소파를 받고 카니발 차를 저렴한 가격에 사기로 하였다. 차가 하나 더 생겨서 기분이 좋다.

**Comment by eyabc** [comment]
- [아티스츠카드 코딩과제 next.js view 작업 하는중](https://github.com/eyabc/music-manager/commit/7d06417133ac50cec9fae78031fc4e786fb285ec)
- 옵치 동아리 회식
