### ISSUE TITLE
2020 09 07

### ISSUE THREAD

**Issue by khw970421** [DKU-STUDY/TodayReview#142]
요즘 안써서 한거라도 미리 쓰는게 나을거 같다.

1. 부스트 코스 웹 프로그래밍 강의 2강듣기 (F12에서 network부분에서 XHR통신(Ajax)부분과 JSONP통신 이해
2. 준일이형 추천하는 유투브 강의듣기 => concurrency랑 parallelism 이해 (운영체제때 솔직히 제대로 이해못했는데 도움되었다.)
3. js engine 작동원리 이해 및 chrome v8 engine => event loop라는게 engine work와 check queue에서 반복해서 주고받아서 event loop라고 하는지 처음 이해 
4. 프로그래머스 level2 잘 풀고 pull request
5. 인공지능 강의듣기
6. 웹프로그래밍 수강정정완료 (휴 AI경진대회랑 내가 이렇게 하는거 집중 더 해야지) 
7. 머신러닝 강의 듣기( 부스트 코스 ->https://www.edwith.org/aipython/lecture/22954/) AI경진대회 반강제로 나가야하니 잘 들어야지
8. 준일이형 pull request 응답 피드백 완료

**Comment by JunilHwang** [comment]
## 회사일
- Mobile API 핫픽스
  - 캐싱처리를 엉뚱하게 해놨다.. ~~멍청이~~
- Internal API에서 Mobile API 제거
  - 이전에 작업해둔 브랜치가 있었는데 멍청하게도 다른 브랜치랑 합쳐버렸다.
  - 그래서 릴리즈 하려고 보니까 문제가 있는 것 같아서 다시 작업했다. ~~멍청이~~
- 그리고 크로미움 전용의 줌 2.0을 만들 것 같다... 아마 올해 안에 서비스 될 수도..

## 블랙 커피 스터디
- Step3 시작. 오늘 내로 끝내야지

**Comment by Jaewon0702** [comment]
Programmers
==============
[level 01. 최대공약수와 최소공배수](https://github.com/DKU-STUDY/Algorithm/pull/434)
Euclidean Algorithm을 사용하였다. 무려 기원전 300년에 만들어진 알고리즘이다! b를 r로 나눈 나머지 r'를 구하고, 다시 r을 r'로 나눈 나머지를 구하는 과정을 반복하여 나머지가 0이 되었을 때 나누는 수가 a와 b의 최대공약수이다. 최소공배수 = 두 자연수의 곱/최대공약수인 것을 이용하였다.

인문학 독서
==========
Jordan Peterson, <12 Rule Of Life : Antidote To Chaos>
-------------------------------------------------------
법칙 5. 아이를 제대로 키우고 싶다면 처벌을 망설이거나 피하지 말라.
5. 훈육과 처벌
"아이가 두려움과 고통을 느끼지 않았으면 좋겠다고 바라는 것은 잘못된 것이다. 배워야 할 것들을 잘 배울 수 있도록 아이의 학습 능력을 길러주는 것이 훨씬 현명하다."
**"당신 자녀의 훈육은 당신이 맡아야 한다. 그렇지 않으면 그 책임을 냉혹하고 무정한 세상에 떠넘기는 것이다."**
"다섯 살이 될 때까지 올바르게 행동하는 법을 배우지 못하면 친구를 사귀는 데 평생 어려움을 겪는다."
"개인의 정신 건강은 공동체에 얼마나 순조롭게 진입했는가에 큰 영향을 받는다."

6. 필요한 최소한의 힘
'오컴의 면도날' "무엇인가를 설명할 때 꼭 필요한 것 이상을 가정해서는 안 된다."
훈육 원칙
    **1. 가장 중요한 최소한의 규칙만 남겨라**
ex )'자기방어가 아닌 경우에는 물어뜯거나 때리거나 발로 차지 마라.' '친구들과 나누고 공유하는 법을 배워라.' '다른 사람에게 좋은 일이 생기면 함께 즐거워해라.'
    **2. 그 규칙을 적용할 때 최소한의 힘만 사용해라**
"어떤 아이는 단호한 말 한마디에도 온 몸이 얼어붙는다."
"체벌은 어떤 이유로도 용납해서는 안 된다."라는 주장에 대한 반박
    1. 도둑질이나 폭력 같은 잘못된 행위는 제재해야 한다는 데 많은 사람이 공감한다.
    2. 폭력적인 체벌뿐만 아니라 그 외 여러 형태의 심리적 사회적 제재 수단이 있다.
    3. 사태의 악화를 막기 위해서 신속하고 확실하게 제재해야 하는 행동들이 있다.
ex) 전기 콘센트에 포크를 꽂는 아이, 차가 붐비는 마트 주자장에서 뛰어다니는 아이
"잘못된 행동에 대한 처벌은 나이 들수록 점점 가혹해진다."
"훈육 자체를 포기하지만 않으면 효과적이지 않아도 괜찮다. **잘못된 행위가 교정되지 않으면 효과적이지 않아도 괜찮다.**"
'타임아웃' - 규칙 "네가 올바르게 행동할 수 있으면 곧바로 우리와 어울릴 수 있다."

4. 훈육 원칙의 재정리
    1. 중요한 최소한의 규칙만 남겨라
    2. 그 규칙을 적용할 때 최소한의 힘만 사용하라.
    3. 부모가 함께 노력해야 한다.
불면증, 허기, 직장 스트레스 등은 그것 하나만으로도 판단과 행동에 커다란 영향을 미친다. 이럴 때 아이가 짜증을 내고 불평을 한다면 아이와 부모는 '돌아오지 않는 다리'를 건널 확률이 높아진다.
    4. 부모는 자신도 냉정하고 교만하고 원망하고 분노하고 기만하는 인간이라는 사실을 알아야 한다.
"부모가 자신의 한계를 진실로 인정한다면, 자녀의 잘못을 마냥 포용할 만한 역량이 안 된다는 것을 인정한다면 부모가 힘을 합쳐 적절한 훈육 전략을 세울 수 있다."
    5. 부모에게는 현실 세계의 대리인으로 행동할 의무가 있다.
"부모에게는 자녀의 행복을 보장하고 창의력을 키워주며 자긍심을 복돋워야 할 책임이 있다."
**"높은 수준의 사회성이 갖춰진 후에야 개인의 정체성도 의미를 갖는다."**

5. 착한 아이와 책임을 다하는 부모
"갈등과 책임을 피하려면 부모의 비겁한 양육보다 주변 사람들의 격려가 아이의 개성을 형성하는 데 더 큰 역할을 한다."
**"어른이라도 잘못을 했으면 사과해야 하고, 더 나은 방법을 끊임없이 찾고 배워야 한다."**
"분명한 규칙은 자녀 성장에 도움을 줄 뿐만 아니라 차분하고 합리적인 부모가 되는데도 큰 역할을 한다."
"헌신적이고 용기 있는 부모가 자녀에게 줄 수 있는 가장 큰 선물은 올바른 훈육이다."
"아이를 제대로 키우고 싶다면 처벌을 망설이거나 피하지 말라."

학과 공부
=============
객체지향 프로그래밍
----------------------------
학과 수업은 C++로 진행하지만, <Python for Beginner>책에 관련 내용이 있길래 공부하였다.
[클래스의_완전한_작동_구현](https://github.com/Jaewon0702/Python_for_Beginner_Turtle/blob/master/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5_%ED%81%B4%EB%9E%98%EC%8A%A4%EC%9D%98_%EC%99%84%EC%A0%84%ED%95%9C_%EC%9E%91%EB%8F%99_%EA%B5%AC%ED%98%84.py)

1. Class의 개념
Class 클래스명 : 
field : 변수

Method
def upSpeed(self,value):
self 변수를 사용한다는 표시이다. 매개변수는 value 뿐이다.

class -> 자동차 설계도
instance -> 실제 자동차 생산

영어 노래 공부
===========
[Imagine Dragons - Warriors](https://www.youtube.com/watch?v=fmI_Ndrxy14&list=RDfmI_Ndrxy14&start_radio=1)
----------------------------------------------
As a child you would wait
And watch from far away
But you always knew that you'd be the one that work while they all play
In youth you'd lay awake at night and scheme of all the things that you would change
**lay : put down, especially gently or carefully, Scheme : make plan something intent to do illegal or wrong** 
But it was just a dream!

Hear we are, don't turn away now, we are the warriors that built this town from dust

The time will come when you'll have to rise
Above the best and prove yourself
Your spirit never dies!
Farewell(= goodbye), I've gone to take my throne(왕좌) above
But don't weep( = cry) for me 'Cause this will be the labor of my love'

Hear we are, don't turn away now, we are the warriors that built this town from dust

**Comment by eyabc** [comment]
- 코드스피츠 async await 강의 마무리, 에러 핸들러 정리
- 블랙커피 온라인 스터디
