### ISSUE TITLE
2020 10 05

### ISSUE THREAD

**Issue by Siyoung-Yang** [DKU-STUDY/TodayReview#170]
9월의 책 클린코드에 대한 리뷰 작성 완료! 책 내용이 많이 어렵다..

**Comment by JunilHwang** [comment]
@Siyoung-Yang 리뷰 읽어봤는데 재밌네요 ㅋㅋ 읽기 어려웠을텐데 수고하셨습니다!
다른 분들도 여유 있을 때  한 번 읽어보세요!
https://github.com/DKU-STUDY/Book-of-the-month/issues/12#issuecomment-703653710

***

## 오늘은 휴가
- 연차 사용
- 아직 중도입사자 연차 10개가 남았다.
- 그래서 매주 금요일마다 신청해놨다
- 남은 한 해는 주 4일 근무 👍 

## 코드리뷰
- 밀린 코드 리뷰를 싹다 해놨다.
- 그래도 이제 블랙커피스터디, tdd 리뷰가 끝나서 한가로운편
- 이번달도 알차게 보내봅시다!

## 리액트 스터디
- 리액트 코드리뷰를 반영 중

**Comment by eyabc** [comment]
웍스모바일 이력서를 작성하였다.. 흠 오늘하루도 끝

**Comment by Jaewon0702** [comment]
오늘 할머니 마지막으로 보내드리고 왔다. 이후에 서울에 가서 카니발이랑 몇몇 가구들을 인수해왔다. 
9시 50분에 독서토론모임을 아직 하고 있길래 11시 30분까지 참여하였다. 

예술과 예술가를 분리해서 봐야 하는가?

조두순 같은 흉악범조차도 포용하고 우리 사회의 일원으로 받아들여야 하는가?
