### ISSUE TITLE
2020 12 25 🎄

### ISSUE THREAD

**Issue by JeonghyunLee99** [DKU-STUDY/TodayReview#251]

**Comment by Jaewon0702** [comment]
High Hopes, Panic! At The Disco
------------------------------------------------
Had to have high, high hopes for a living.
Shooting for the stars when I couldn't making a killing
Didn't have a dime but I always had a vision.

Always had high, high hopes
Had to have high, high hopes for a living
Didn't know how but I always had a feeling
I was gonna be that one in million.

Always had high, high hopes.

Mama said 'Fulfill the prophecy( == prediction) 예언을 성취하라'
Be something greater
Go make a legacy( = an amount of money left to someone, 유산)
Manifest( = clear or obvious to eye or mind, 증명하다) destiny
Back in the days
we wanted everything, wanted everything

Mama said
Burn your biographies
Rewrite your history
Light up your widest dreams.
Museum Victories, everyday.
we wanted everything, wanted everything.

Mama said don't give up, it's a little complicated.
All tied up. no more love and I'd hate to see you waiting.

Had to have high, high hopes for a living
Didn't know how but I always had a feeling
I was gonna be that one in million.

It's uphill for oddities. uphill( = life is harder if you don't fit in.), oddity( = a strange) 괴짜들에게는 어려운 길이 될거야.
Stranger crusaders(=십자군, 혁명가) ain't ever wannabes
The weird(이상한) and the novelties(특이한) don't ever change.
We wanted everything, wanted everything.
Stay up on that rise and never come down, oh.

Mama said don't give up, it's a little complicated.
All tied up, no more love and I'd hate to see you waiting
They say it's all been but they haven't seen the best of me.
So I got one more run and it's gonna be a sight to see.

Had to have high, high hopes for a living
Didn't know how but I always had a feeling
I was gonna be that one in million.

공자, <논어>
---------------------------
제 15편 위령공

11. 사람이 멀리 내다보며 깊이 생각하지 않으면, 반드시 가까운 근심이 있게 된다.
14. 자신에 대해서는 스스로 엄중하게 책임을 추궁하고, 다른 사람에 대해서는 가볍게 책임을 추궁하면, 원망을 멀리 할 수 있다.
15. 어찌하면 좋을까를 고민하고 노력하지 않는 사람이라면, 나도 정말 어찌할 수가 없다.
18. 군자는 자신의 무능함을 근심하지, 남이 자기를 알아주지 않음을 근심하지 않는다.
19. 군자는 죽은 뒤에 이름이 일컬어지지 않을까를 근심한다.
20. 군자는 일의 원인을 자기에게서 찾고, 소인은 남에게서 원인을 찾는다.
23. 한마디 말로 평생토록 실천할 만한 것이 있습니까?
그것은 서(恕)로다! 자기가 원하지 않는 것을 남에게 하지 않는 것이다.
26. 고묘한 말은 덕(德)을 어지럽히고, 작은 일을 참지 못하면 큰 일을 그르친다.
27. 많은 사람들이 미워한다 해도 반드시 잘 살펴보아야 하며, 많은 사람들이 좋아한다 해도 반드시 잘 살펴보아야 한다.
29. 잘못이 있어도 고치지 않는 것, 이것이 바로 잘못이다.
31. 군자는 도(道)를 걱정하지, 가난을 걱정하지 않는다. 도를 추구하며 성실하게 공부하다 보면 녹봉은 자연히 따라오게 된다.
32. 군자는 작은 일은 잘 못해도 큰 일은 맡아 할 수 있고, 소인은 큰 일은 감당 못해도 작은 일은 잘할 수 있다.
38. 가르침에 있어서는 차별을 두지 않는다.
40. 말은 뜻을 정확히 표현하면 그만이다.

제 16편 계씨
1. 구야! 군자는 자기가 원한다고 솔직하게 말하지 않고 그것을 위해서 말을 꾸며대는 것을 미워한다.
4. 정직한 사람을 벗하고, 신의가 있는 사람을 벗하고, 견문이 많은 사람을 벗하면 유익하다. 위선적인 사람을 벗하고, 아첨을 잘하는 사람을 벗하고, 말만 잘하는 사람을 벗하면 해롭다.
5. 예악(禮樂)의 절도를 따르기 좋아하고, 남의 좋은 점을 말하기를 좋아하고, 현명한 벗을 많이 사귀기를 좋아하면 유익하다. 교만하여 즐기기를 좋아하고, 방탕하게 노는 데 빠지기를 좋아하고, 주색에 싸여 음란하게 놀기를 좋아하면 해롭다.
7. 군자에게는 세 가지 경계해야 할 일이 있다. 젊을 때는 혈기가 안정되지 않으므로 정욕(情慾)을 경계해야 한다. 장년이 되어서는 혈기가 막 왕성해지므로 다툼을 경계해야 한다. 노년이 되어서는 혈기가 이미 쇠약해졌으므로 탐욕을 경계해야 한다.
8. 군자에게는 세 가지 두려워해야 할 일이 있다. 천명(天命)을 두려워해야 하고, 위대한 성인(聖人)을 두려워 해야 하며, 성인을 말씀을 두려워 해야 한다.
9. 태어나면서부터 아는 사람은 최상이고, 배워서 아는 사람은 그 다음이며, 곤란한 지경에 처하여 배우는 사람은 또 그 다음이고, 곤란한 지경에 처하여도 배우지 않는 사람은 백성들 중에서도 최하이다.
10. 군자에게는 항상 생각하는 것이 아홉가지가 있다. 볼 때에는 밝게 볼 것을 생각하고, 들을 때에는 똑똑하게 들을 것을 생각하며, 얼굴빛은 온화하게 할 것을 생각하고, 몸가짐은 공손하게 할 것을 생각하며, 말을 할 때는 진실하게 할 것을 생각하고, 일을 할 때는 공경스럽게 할 것을 생각하며, 의심이 날 때는 물어볼 것을 생각하고, 성이 날 때는 뒤에 겪을 어려움을 생각하며, 이득될 것을 보았을 때에는 그것이 의로운 것인가를 생각한다.
13. 시를 공부하였느냐?
시를 공부하지 않으면 남들과 말을 잘 할 수 없다.
예(禮)를 공부하였느냐?
예를 공부하지 않으면 남들 앞에 설 수가 없다.

제 17편 양화
2. 사람의 타고난 본성은 서로 비슷하지만, 학문과 수양을 어떻게 하는가에 따라 차이가 나게 된다.
6. 천하에서 다섯 가지를 실천할 수 있으면 그것이 인(仁)이다.
공손함, 너그러움, 미더움, 민첩함, 은혜로움이다.
공손하면 업신여김을 받지 않고, 너그러우면 많은 사람들의 마음을 얻으며, 미더우면 사람들이 신임하게 되고, 민첩하면 공이 있게 되고, 은혜로우면 사람을 부릴 수 있게 된다.
