### ISSUE TITLE
2021 01 01 🐮

### ISSUE THREAD

**Issue by JeonghyunLee99** [DKU-STUDY/TodayReview#258]

**Comment by Jaewon0702** [comment]
DKU 지역거점 스타트업 온라인 창업교육
------------------------------------------------------
I. 기업가 정신
1강 기업가 정신과 스타트업
기업가 정신과 스타트업이란?
새로운 사업 기회 포착, 사업 기회 실현
조직 - 실행 - 위험감수
START - UP : 시장의 수요를 충족하거나 문제를 해결할 수 있는 사업모델을 개발하는 것이 목표

2강 스타트업 후배들에게 들려주고 싶은 이야기
대학을 중퇴하고 기업가 정신의 표상이 된 젊은이.
"포기하지 않는 것만으로도 스타트업은 놀랄 만큼 멀리갈 수 있다."
엑셀레레이터, 와이콤비네이터 폴 그레이엄
도전, 위험 감수, 실패를 두려워하지 않는 자세

기업가 정신 4가지 역량
1. 성취 욕구: 높은 성과를 내기 위해 도전적인 목표를 설정하고 이를 달성하고자 하는 욕구
2. 통제 능력: 주위에서 일어나는 일들에 대해 통제하고 관리할 수 있다고 믿는 것.
3. 위험 감수성: 어떤 사업을 할 때 불확실한 결과가 예상됨에도 불구하고 과감하게 도전하려는 위치
4. 창의성: 남들이 미처 생각하지 못한 걸 묻고 답해 보는 것

3강 에어비앤비의 바퀴벌레 정신
바퀴벌레 정신의 시작, 4년만에 숙박 기업의 아이콘으로
민주당 전당대회 숙소 부족 상태 해결.(기자에게 천 통의 메일을 보냄.)
시리얼로 종자돈을 벌다.  

4강 역사 속 기업가 정신 이야기
조선 최고의 장군 이순신의 위험 감수성
우회하지 않고 직진하는 리더쉽이 필요한 이유
위험을 감수해야 큰 성과가 따르기 때문.
해상왕 장보고 장군의 개척 정신
민간무역
장보고 장군이 해상왕으로 평가받을 수 있었던 이유.
기존의 고정 관념에 사로잡히지 않고, 다른 사람이 미처 보지 못한 가능성을 보고 끝없이 도전했기 때문.

Coldplay, Viva La Vida(long live life.)
---------------------------------
I used to rule the world
Seas would rise when I gave the world
Now in the morning I sleep alone.
Sweep the streets I used to own.

I used to roll the dice.
Feel the fear in my enemy's eyes
Listen as crowd(= a large number of people. ) would sing.
"Now the old king is dead! Long live the king!"

One minute I held the key.
Next the walls were closed on me.
And I discovered that my castles stand upon pillars(= a tall vertical structure of stone, wood or metal.) of salt and pillars of sand.

I hear Jerusalem bells a ringing
Roman Cavalry(기병대) choirs(= An organized group of singers. 콰이얼-) are singing. 
Be my mirror, my sword and shield
My missionaries in a foreign field

For some reason I can't explain
Once you'd go there was never
Never an honest word.
And that was when I was ruled the world.

It was the wicked(사악한) and wild wind.
Blew down the doors to let me in.
Shattered(= To break suddenly into many small pieces) windows and the sound of drums.
People couldn't believe what I'd become.

Revolutionaries wait for my head on a silver plate.
Just the puppet(a person, party or state under the control of another person, 꼭두각시 인형) on a lonely string

I hear Jerusalem bells a ringing
Romans cavalry choirs are singing
Be my mirror, my sword and shield
My missionaries in a foreign filed

For some reason I can't explain
I know Saint Peter won't call my name.
Never an honest word.
But that was when I ruled the world.

안영옥, <돈키호테의 말>
-----------------------------------
내 의지가 원하는 것을 싫어하도록 설득해 보아야 헛수고하는 것으로 결국 너희들은 지치고 말 것이야. 고생은 셀 수 없을 정도로 많지만 또한 그것으로 얻는 행복도 무한하다는 것 역시 알고 있단다.
속편 6장

비교하는 삶
어떤 종류의 비교든 비교라는 것은 모두 증오스러운 것임을 이미 아시지 않소. 그런데 뭣 때문에 누구를 누구와 비교하는지 모르겠소다.
속편 23장
자기 삶에 충실하다면 타인과의 비교는 무의미해진다.

행복할 시간이 많지 않다.
사람들이야 저 좋을대로 말하라고 하게. 내가 이런다고 해도, 무지한 사람들은 나를 책망할지 모르지만 준엄한 사람들이 벌을 내리지는 않을걸세.
전편 25장
자시 자신만의 가치를 남기고 나를 둘러싼 세상의 일에 시간을 허비하지 말아야 한다.

황금 시대라는 행복한 세기에 살았던 사람들은 네 것, 니 것이라는 이 두 가지 말을 몰랐기 때문이오. 모든 것이 다 공동 소유였소. 맑은 샘과 강물은 맛있고 깨끗한 물을 사람들에게 아낌없이 베풀었소. 모든 것이 화평했고, 모두가 의가 두터웠고, 모든 것이 조화로웠소.
전편 11장

가난한데도 만족하며 살 수 있는 사람은 하나님으로부터 많은 것을 받은 사람임이 틀림없다.

나의 가치를 존중하기
사람들이 스스로를 귀하게 여기지 않는다면 어느 누구도 그를 귀하게 생각하지 않는다네.
전편 21장
돈키호테는 산초에게 일러준다.
빼어난 덕이 있으면 어디에서든 추적을 당하기 마련이다. 과거 유명인들 가운데 악의에 찬 중상모략을 당하지 않은 사람은 거의 없었다. 아니, 한 사람도 없었다.
속편 2장

산초가 말한다.
저는 왕을 제거하지도, 왕을 세우지도 않습니다. 다문 저는 저를 도울 뿐이죠. 제가 저의 주인이니까요.
속편 60장

나와 싸워 이기는 법
자신을 이기는 것이야말로 인간이 바랄 수 있는 가장 큰 승리란다.
속편 72장
우리가 죽여야 할 것들은 개인에게서 보이는 오만이요, 관대하고 용감한 가슴에 들어 있는 시기심이며, 평안한 영혼과 태도에 깃든 분노와 우리가 적게 먹고 잠을 충분히 자지 못하는 데서 오는 폭식과 잠이고, 음탕함과 호색이며, 게으름이라네.
속편 8장

명예를 아는 자
지난 해의 둥지에는 이미 올해의 새가 없는 법이요.
속편 74장
돈키호테는 자신이 세상에 내리고자 한 가치가 불가능함을 알게 된다. 성이라고 믿었던 것이 객줏집이고 공주라고 믿었던 것이 하녀라는 것을 알게 된다. 자기가 믿었던 세상이 무너진다. 믿음을 잃는 것보다 더 큰 불행은 없다는 것이다. 그래서 돈키호테는 믿음의 영웅이기도 하다.

비록 목숨을 잃는 한이 있더라도, 진리를 지키고 지지하는 자가 되어야 한다네.

<스스로를 등불로 삼고, 스스로를 의지하라.>
불교경전, <대반열반경>

주막, 부인, 딸 마리토르네스
맘브라노 투구인가? 놋대야인가?

당신이 앉은 자리가 상석이다.
내가 어디에 앉든 내가 앉는 자리가 상석이 되니까.
속편 31장

내용이 부실하면 포장이 거창하다.

2. 어떻게 살고, 어떻게 죽을 것인가
양심이 이끄는 삶
자네는 자네 양심에 따라 살면 되는 거라네.
속편 55장

인생의 재미
걱정스러운 마음으로 산다는 것은 즐거운 일이 아니다.
속편 1장
(병석에서 일어나도록) 할 수 있는 모든 방법을 동원하여 그를 즐겁게 해주려고 노력했다.
속편 74장
과잉 보상: 어떤 행위가 보상을 위한 수단이 되면 즐거움이 사라진다.

어렸을 때 막연히 재미있고 좋아서 찍어나갔던 점들이 나중에 선으로 이어진 것을 보았다.
스티브 잡스, 스탠포드 대학 졸업식 연설 中

**Comment by khw970421** [comment]
1. 토익 공부 
	분사 
    1)꾸며주는 대상 찾기( 분사구문은 주어찾기)
    2) 수동(~된)/능동(~한) 찾기

	would be happy to => 기꺼이 ~하다
    take care of => 처리하다
    
2. JS-study 피드백 (기본 브라우저를 막는것에 addEventListener는 해당하지않는다!)

3. 생활코딩 tensorflow.js 강의 듣기

4. React 공부 ES6의 중요성 

5. [공공데이터 사용방법](https://velog.io/@khw970421/%EA%B3%B5%EA%B3%B5%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B8%B0)
