### ISSUE TITLE
2020 상반기 대학 방학 일기 

### ISSUE THREAD

**Issue by eyabc** [DKU-STUDY/TodayReview#312]

**Comment by dkdlelk99** [comment]
* ## 12월
기말고사도 끝났겠다, 2021년에 무엇을 할지 고민하며 열심히 놀았습니다.


* ## 1월
'내가 하고싶은 일이 뭘까'에 대해 깊게 고민해봤습니다.
내가 잘하는 일이 무엇인지, 좋아하는 일이 무엇인지 다시한번 생각해보았습니다.

긴 생각 끝에 나온 결론 : 일을 사랑하자, 좋아하고 잘 하는게 뭔지 모르겠으면 직접 해보면서 확인해보자

방학 목표
Udemy
인도 아저씨가 알려주는 자료구조 + 알고리즘 강의
web programming을 학교에서 수강하긴 했지만 부족하다고 느껴져서 옛날에 사놓은 강의
책
초청강사로 저번학기에 강연해주신 이정윤 박사님이 알려주신 책 hands-on-machine
원규님이 스터디 진행하시는 종만북도 보고싶은데 여기서 더하면 과욕인듯 하여 포기..

그렇게 굳은 각오로 2021년을 시작했지만...

### 건강 악화
* 목디스크가 제대로 도짐

어느정도 일찍 일어나는게 습관화 되서 7~8시에 눈은 뜹니다.
근데 통증 때문에 침대에서 몸을 일으키는데 거짓말 하나도 안하고 30분이 넘게 걸렸습니다..ㅠㅠ
걸어다니는 것도 어정어정 걸어다녀야되고 옆을 봐야되면 목을 못돌리고 허리를 돌려서 시야를 돌렸습니다.
뼈를 칼로 긁는 듯한 날카로운 통증이 지속되서 목디스크 전문 병원을 찾고 약 100만원 가까이 깨졌습니다.
병원에서 8주정도 본다고 했는데 앞으로도 저정도 깨질 예정입니다.

의사 선생님이 노트북이랑 폰도 당분간 보지 말라고 하셔서 꽤 못봤습니다.
1월 4째주부터 갑자기 커밋이 끊긴 이유입니다.

# 여러분 건강 챙기면서 개발하세요.
여기부턴 잔소리좀 하겠습니다. ~나이도 어린놈이 죄송합니다.~ 근데 저처럼 안아프셨으면 좋겠습니다.
마음잡고 공부하려고 하는데 몸이 아파서 공부 못하면 억울해요.
## 1. 노트북, pc와 눈의 각도는 수직이 좋습니다.
화면에 집중하다보면 무의식적으로 목이 앞으로 빠지는 경우가 많습니다. 조심하세요.
평소에 스마트폰 보실때도 마찬가지입니다. 팔 아파도 얼굴까지 들어올려서 보세요.

## 2. 간단한 운동으로도 목디스크는 예방할 수 있습니다.
열심히 공부하다가 가끔 딴생각 날 때 하기 좋습니다.
주요 포인트는 목에 힘을 빼는 것입니다.
제가 다니는 병원에서 자체적으로 유튜브를 운영하길레 링크 첨부합니다.
  ### 1. 도리도리 운동
https://www.youtube.com/watch?v=eReIEoieQsQ&ab_channel=%EB%AA%A8%EC%BB%A4%EB%A6%AC%ED%95%9C%EB%B0%A9%EB%B3%91%EC%9B%90
  ### 2. 으쓱으쓱 운동
https://www.youtube.com/watch?v=gf9rvscLaCk&ab_channel=%EB%AA%A8%EC%BB%A4%EB%A6%AC%ED%95%9C%EB%B0%A9%EB%B3%91%EC%9B%90

## 3. (권장) 30분에 1분씩이라도 자리에서 일어서 계세요.
현대인의 대부분이 앉아서 생활을 합니다. 문제가 되는 부분은 허리를 지탱해주는 장요근입니다.
지속적으로 오래 앉아있게 되면 장요근이 짧아져서 척추를 지탱하는 중요한 힘이 빠지게 됩니다.



* ## 2월
어느정도 통증이 나아져서 이번주부터는 알고리즘을 풀 수 있을 것 같습니다!
그런데 1월 마지막주에 한문제도 못풀어서 규칙상 2월에는 참여를 못하겠네요.. ㅠㅠ


## 마무리
어쩌다 보니 회고가 아니라 잔소리가 내용의 절반을 넘게 채워버렸네요..
그래도 혹여나 이 글을 보신다면 여러분 본인의 목, 허리 건강을 다시 한 번만 살펴주세요. 
이 스터디에 들어와 계신 분들이라면 앞으로 최소 n*10년은 컴퓨터를 들여다보실텐데 
목, 허리가 삑나면 진짜 진짜 큰일납니다... 😢 

남은 방학기간, 스트레칭 열심히 하면서 의사 선생님이 허용한 시간 내에서 열심히 공부하려합니다.
여러분도 화이팅~~   :D

**Comment by JeongShin** [comment]
이번 겨울방학은 내 인생에서 제일 개발도 많이하고 고민도 많이 했다.
작년 9월을 시작으로 인턴십을 시작으로 스타트업 개발 대행사 에서 일을 시작한 뒤로 개발을 본격적으로 시작했다. 

회사를 다니면서 얻은 제일 큰 장점은 개발에 대한 두려움이 없어졌고 개발이 습관이 된게 제일 큰 장점인 것 같다. 
그러다보니 자연스럽게 어떤 개발을 하고 어떤 회사에서 일을 하고 싶은지 고민이 생겼다. 

일단 지금 다니고 있는 회사는 내가 원하면 계속 다닐 수 있을 것 같고 회사가 가는 방향도 점점 좋은 방향으로 가고 있고 새로운 기술도 새로 시도해보려는 과정에 있고 몇몇 회사 분들과 스터디를 진행하면서 회사에서 계속 남아서 개발을 할지 아니면 회사를 그만두고 더 좋은 회사를 가기 위한 준비를 하는게 맞을지가 젤 큰 고민이다. 

그래서 내린 결론은 회사는 계속 다니면서 스터디 & 공부를 병행 하면서 다른 좋은 기회가 보이면 계속 지원 해보는 더 피곤한? 방법을 선택 했는데 
앞으로 어떤 개발을 하게 되고 어떤 회사를 가게 될지 걱정이 되기도 하고 잘 모르겠다. 

어쨋든 아직 졸업 하려면 1년 남았는데 학교 다니기가 너무 싫어져버린건 큰 문제인 거 같다.

**Comment by 6047198844** [comment]
졸업 후 어떤 방식으로 공부해야하는가에 대해서 고민이 많았습니다.
여러 공부 방법을 시도해봤습니다. 많은 방법중 책으로 하는 공부가 확실한 정보와 체계적인 구성을 가지고 있다고 느꼈습니다. 따라서 책으로 하는 공부를 택했습니다. 
또한, 구글링으로 정보를 찾는것은 쉽지만 제 학습 단계가 올바른 정보를 취사선택해서 공부 할 수 있는 단계는 아닌것같습니다. 책으로 하는 공부는 포기하지만 않는다면 좋은 방법이라고 생각이 들었습니다.

이번년도 목표는 웹 개발 분야에 대해서 많은 책을 읽는것입니다.

현재 1월부터 2월까지 공부하고 있는 주제와 책은 다음과 같습니다.
- 자바 / 자바의 정석
- 알고리즘/ 알고리즘 문제 해결 전략
- 객체지향 / 객체지향의 사실과 오해 , 객체지향의 이해와 원리

앞으로 공부할것은 다음과 같습니다.
- JSP & Servlet / 처음 해보는 Servlet&JSP
- 디자인패턴 / Head First 디자인패턴

1년 동안 공부한다는 마음가짐으로 취준을 준비하고 있습니다. 아침에 엄마랑 산책하고 도서관에서 공부하고 집오고 하는 일상의 반복이네요.
아직 시작단계지만 정말 운이 좋게도 3번의 면접을 봤고 모두 떨어졌습니다. 앞으로 이런 행운이 올지는 모르겠네요. 인생의 소중한 기회들을 놓쳐버린듯한 느낌 ( NHN 전환형 인턴 최종면접(교내) / 단쿠키 면접 / 카카오 추천팀 전환형 인턴 최종면접 )
처음에는 떨어진것에 대해서 정말 상심했는데 계속 떨어지다보니 무뎌지더라구요. 제가 생각해도 제가 부족한걸 어쩌겠어요.
결과도 중요하지만 떨어질때마다 오기가 생기고 공부시간도 계속 늘어가는것을 보면 떨어지더라도 면접까지 가는것도 돈으로 살수없는 행운인것 같습니다. 더 공부하면 언젠간 되겠죠 뭐. 

다들 노력하신만큼 잘되시길 기원합니다.

**Comment by JeongShin** [comment]
@6047198844 
저랑 비슷한 고민을 하고 계신거 같아 공감이 많이 가네요. 알고리즘 풀이도 꾸준히 하시는거 같던데 
잘 준비해서 꼭 잘 되시길 바랍니다. 파이팅하세요!! 😃😄
