### ISSUE TITLE
2020 05 01

### ISSUE THREAD

**Issue by dkdlelk99** [DKU-STUDY/TodayReview#7]

**Comment by dkdlelk99** [comment]
2020년 5월이 되었다. 
작년 5월보다는 충실하게 살고 있는지 되돌아 봤다.
스터디도 하고 있고 작년에는 쓸줄도 모르던 깃헙으로 1일 1커밋도 5일간 유지 하고있다.
아직 한참 부족하다고 느끼긴 하지만 안하는건 아니니까! 긍정긍정!!

날씨가 벌써부터 더워지려한다.
동생은 선풍기를 빼왔다. 천재다.

빠르게 알고리즘 문제 하나 풀고 월요일 오전에 있을 모바일플랫폼 공부와 일요일 제출인 db기초 과제를 해야한다.

하루 하나만 하자! 라는 마인드로 한문제씩 풀다보니까 욕심이 생겨서 어제는 1.5개 정도 풀은것같다.
그래서 오늘 날먹했다. 급한불 꺼지면 더 욕심내볼까 한다. 내 풀이를 보고 다른분들 풀이를 보면 기초가 많이 모자라다는 생각이 든다. 인프런에서 듣던 강의 찾아서 들어야겠다.
그리고 매일매일 코드 봐주시는 준일님 무한감사 ㅠㅠ

**Comment by eyabc** [comment]
바다를보며 멍때림

**Comment by JunilHwang** [comment]
@dkdlelk99 이재동 교수님의 늪에 빠지셨네요.. 인강이라서 다행. 그런데 석균어도 있네요. gg
@eyabc 공부를 하시게

- 바닷가라서 그런지 더운데 시원하고 시원한데 덥다.

- 코드리뷰를 하다 보면 내가 생각하지 못했던 방식으로 풀이하는 것들을 알게 되기 때문에 신기하기도 하고 즐겁기도 하고 자극도 된다. 그러니 각자 풀이하는 언어가 겹칠 경우 굳이 제가 아니더라도 서로 코드리뷰를 합시다!

**Comment by JeongShin** [comment]
@JunilHwang 다른 사람의 코드도 찾아보고 리뷰해보겠습니다. 

알고리즘 문제푸는데 오랜 시간이 걸리는데 대부분의 시간이 자바스크립트 문법, ES6 등을 찾아보는데 시간이 많이 걸린다. 점점 익숙해질때까지 꾸준히 문제를 풀어봐야 할것 같다. 

준일이형이 웹 관련 스터디 순서를 알려줬는데 갈길이 너무 멀다 느껴지지만 항상 마음이 급해지면 더 하기 싫어지는 편이라 가벼운 그냥 천천히 해보자는 마인드로 하나씩 해봐야겠다.. 

10만원대 주고 산 맥미니 2010mid 제품 맥북 배터리 싸이클 다는게 아까워서 중고로 샀더니 이틀만에 파워가 안들어온다. 역시 10년된 제품이라 그런가.. 애플 서비스 센터 가져가봤자 수리비가 더 나올꺼 같다. ㅠ

**Comment by JunilHwang** [comment]
@JeongShin 
첨언을 하자면

- Q: React를 배우고 싶습니다.
- A: React는 익히기 어려운 프레임워크입니다. 그래서 다음과 같은 개념들을 먼저 익혀야됩니다.
  - 객체지향 개발론 (객체지향 문법이 아닙니다)
     - 객체지향 SOLID 원칙
     - Dependency Injection
  - 디자인 패턴(Observer, Composite, Factory, Singleton, Strategy, Template ...)
  - MVVM(Model - View - ModelView) 패턴
  - ECMAScript6+
    - scope, closure, promise, prototype, ...
  - 함수형 프로그래밍 (불변성)
  - 번들러(Webpack), 트랜스파일러(Babel)

그리고 어차피 React를 하면서 위에 언급한 것들은 자연스럽게 접할 수 밖에 없습니다!
