### ISSUE TITLE
2020 07 03

### ISSUE THREAD

**Issue by sAp00n** [DKU-STUDY/TodayReview#73]
드디어 다시 시간이 나서 복귀 연습으로 간단한 문제 풀이 해서 pr 하려고 했는데,,
새상에 이전 PR이 아직도 안닫혀있었네...
후딱 머지시켰습니다.
다음주 부터는 다시 본격적으로 스터디 진행해보자 한다.
만약 일과시간 내에 시간이 나지않아도...
그러면 수면시간을 줄이는 방법밖에 없겠지만.

**Comment by eyabc** [comment]
* 알고리즘 한문제 풀고, 스피치 강의도 하나듣고, 국민체조도 하고, 목표한 청소도 달성!!
* 밑바닥 부터 시작하는 컴퓨팅 시스템 16페이지 읽음!

**Comment by JunilHwang** [comment]
## 회사일
- 확장프로그램 1.1.5.2 버전 게시 완료 (https://chrome.google.com/webstore/detail/bghgeookcfdmkoocalbclnhofnenmhlf)

## 디스코드 봇
- 디스코드 봇을 이용하여 github에 pr, issue, push 등이 발생했을 때 메세지를 보내도록 만들었다.
- 봇의 기능만 이용해서는 만들수 없고 봇과 discord api를 이용하여 만들어야 한다.
- 저장소 : https://github.com/JunilHwang/discord-study-bot

**Comment by JeongShin** [comment]
코드 리뷰를 하다보니까 내가 푼 문제도 다시 돌아보니까 잘 생각이 안남 
리뷰하면서 다시 공부하는 시간이 될 수 있어서 좋은거 같음! 

너무 코딩 경험도 없고 해본 프로젝트도 없어서 조급한 마음이 생기지만 
조급해 하지말고  천천히 기초부터 잘 해봐야겠음 ㅠ

내일부터 자바스크립트 코어를 공부해 봐야겠음
