### ISSUE TITLE
2020 07 08

### ISSUE THREAD

**Issue by sAp00n** [DKU-STUDY/TodayReview#78]
### 자료구조

그래프의 인접 행렬,인접 리스트 관련해서 공부중...

### 알고리즘

Semiprime 재도전... 하지만 대실패 오후 시간을 다 투자해봤는데 PR 쓰면서 알게된건 잘못 접근했다고 생각이 든거말고 없다 ㅋㅋ
아예 내일도 다시 코드 다 지우고 종이에 persudo 코드부터 작성해봐야겠다.

**Comment by JunilHwang** [comment]
## 회사일

- CMS 작업 중. 자잘한 기능이 많다보니 한 페이지 만드는데 하루 종일 걸리는 중.. 으악
- 크롬 확장프로그램 관련된 내용도 정리해야되는데.. 언제쯤 할 수 있을까?

## 카카오 면접

- 다음주 수요일에 카카오 면접 예정
- 이번주 토요일까지 면접 과제 제출해야 됨.
- 프레임워크 없이 프레임워크 처럼 만드려고 하니 무지막지하게 귀찮네..

**Comment by JeongShin** [comment]
오늘은 동생 생일에 여러가지 일이 많아서 거의 공부도 못하고 휴식도 못하고 그냥 하루를 날린 느낌 
,,, ㅠ ㅠ

**Comment by eyabc** [comment]
- 알고리즘 lessons.lesson12.EuclideanAlgorithm.ChocolatesByNumbers 을 풀었다. gcd 구하는 공식은 알겠는데.. 왜 이런발견을 했을까는 모르겠다. 알고싶지도 않다...
- js 스터디 리뷰
- 발짝 프로젝트 코드 읽음
